config/routes.rb
Rails.application.routes.draw do
  root 'contacts#index'

  get 'contacts' => 'contacts#index', as: 'contacts'
  get 'contacts/:id' => 'contacts#show', as: 'contact'
  get 'contacts/new' => 'contacts#new', as: 'new_contacts'
  get 'contacts/:id/edit' => 'contacts#edit', as: 'edit_contacts'
  post 'contacts' => 'contacts#create'
  patch 'contacts/:id' => 'contacts#update'
  delete 'contacts/:id' => 'contacts#destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :contact
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one :address

  accepts_nested_attributes_for :address, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :destroy, :update]
  # GET /contacs
  def index
    @contacts = Contact.all
  end

  # GET /contacts/:id
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address
  end

  # POST /contacts
  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: 'Contato Criado com Sucesso!'
    else
      render :new
    end
  end

  # /contacts/:id/edit
  def edit
  end

  # PATCH/PUT /contacts/:id
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: 'Contato Atualizado com Sucesso!'
    else
      render :edit
    end
  end

  # DELETE /contacts/:id
  def destroy
    @usuario.destroy
    redirect_to contacts_url, notice: 'Contato excluido com sucesso!'
  end

  private
    # setar no callback before_action
    def set_contact
      @contact = Contact.find(params[:id])
    end

    #White params // parametros permitidos para a persistencia
    def contact_params
      params.require(:contact)
            .permit(:name, :email, :phone, :description,
                      address_attributes: [:street, :number, :city, :state]
                    )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true)  do |f| %>
  <%= render "layouts/message_form", content: contact %>
  <div  class="row">
      <div class="col-sm-6">
        <%= f.label :name %>
        <%= f.text_field :name, id: :contact_name, class: "form-control" %>
        <%= f.label :email %>
        <%= f.text_field :email, id: :contact_email, class: "form-control" %>
        <%= f.label :phone %>
        <%= f.text_field :phone, id: :contact_phone, class: "form-control" %>
        <%= f.label :description %>
        <%= f.text_field :description, id: :contact_description, class: "form-control" %>
      </div>
      <div class="col-sm-6">
        <%= f.fields_for :address_attributes, contact.address do |address_fields| %>
          <%= address_fields.label :street %>
          <%= address_fields.text_field :street, id: :contact_street, class: "form-control" %>
          <%= address_fields.label :number %>
          <%= address_fields.text_field :number, id: :contact_number, class: "form-control" %>
          <%= address_fields.label :city %>
          <%= address_fields.text_field :city, id: :contact_city, class: "form-control" %>
          <%= address_fields.label :state %>
          <%= address_fields.text_field :state, id: :contact_state, class: "form-control" %>
        <% end %>
      </div>
  </div>
  <br>
  <%= f.submit 'Criar Contato', class: "btn-info pull-left" %>
<% end %>

app/views/contacts/new.html.erb
<h1>Novo Contato</h1>

<%= render 'form', contact: @contact %>

app/views/contacts/show.html.erb
<div class="alert alert-success fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= notice %>
</div>
<div class="row"><!--row-->
    <div class=" col-sm-4"><!--col-->
      <div class="panel panel-default"> <!--panel-->
        <div class="panel-heading">Contato</div>
          <table class="table table-sm"> <!--tabela-->
            <thead>
                <tr>
                  <td> Nome </td>
                  <td><%= @contact.name %></td>
                </tr>
                <tr>
                  <td> Telefone </td>
                  <td><%= @contact.phone %></td>
                </tr>
                <tr>
                  <td> E-mail </td>
                  <td><%= @contact.email %></td>
                </tr>
                <tr>
                  <td> Descrição </td>
                  <td><%= @contact.description %></td>
                </tr>
            </thead>
          </table><!--/tabela-->
      </div><!--/panel-->
  </div><!--col-->
  <div class=" col-sm-4"><!--col-->
    <div class="panel anel-info"> <!--panel-->
      <div class="panel-heading">Endereço</div>
        <table class="table table-sm"><!--table-->
          <thead>
              <tr>
                <td> Rua </td>
                <td><%= @contact.address.street %></td>
              </tr>
              <tr>
                <td> Número </td>
                <td><%= @contact.address.number %></td>
              </tr>
              <tr>
                <td> Cidade </td>
                <td><%= @contact.address.city %></td>
              </tr>
              <tr>
                <td> Estado </td>
                <td><%= @contact.address.state %></td>
              </tr>
          </thead>
        </table><!--/table-->
      </div><!--/panel-->
  </div><!--/col-->
</div><!--/row-->
<%= link_to 'Editar ?', edit_contacts_path(@contact), class: "btn btn-info" %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to "Home", root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Novo Contato", new_contacts_url %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/_message_form.html.erb
<% content.errors.full_messages.each do |message| %>
  <div class="alert alert-error fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nested</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name=viewport content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/header' %>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>